config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: staging
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/jupyter/nbgrader:
      repo: https://github.com/jupyter/nbgrader
environment:
  JPL_KEEPGOING: true
sqa_criteria:
  QC.Acc:
    repos:
      github.com/jupyter/nbgrader:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-cobalt-warthog.sh
        container: qc.acc_cloudy-linen-bear
  QC.Doc:
    repos:
      github.com/jupyter/nbgrader:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-amethyst-bat.sh
        container: qc.doc_cheeky-fuchsia-cheetah
      github.com/jupyter/nbgrader__2:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-cream-guppy.sh
        container: qc.doc_tacky-asparagus-whippet
  QC.Lic:
    repos:
      github.com/jupyter/nbgrader:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-burgundy-sheepdog.sh
        container: qc.lic_messy-champagne-angora
  QC.Met:
    repos:
      github.com/jupyter/nbgrader:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-cobalt-seal.sh
        container: qc.met_leaky-malachite-monkey
timeout: 600
